//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsGSM.GameServer.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsGSM.GameServer.Data.Icon", typeof(Icon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/7dtd.png.
        /// </summary>
        public static string _7_Days_to_Die_Dedicated_Server {
            get {
                return ResourceManager.GetString("7 Days to Die Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/cs.png.
        /// </summary>
        public static string Counter_Strike__1_6_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: 1.6 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/cscz.png.
        /// </summary>
        public static string Counter_Strike__Condition_Zero_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Condition Zero Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/csgo.png.
        /// </summary>
        public static string Counter_Strike__Global_Offensive_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Global Offensive Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/dayz.png.
        /// </summary>
        public static string DayZ_Dedicated_Server {
            get {
                return ResourceManager.GetString("DayZ Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/gmod.png.
        /// </summary>
        public static string Garry_s_Mod_Dedicated_Server {
            get {
                return ResourceManager.GetString("Garry\'s Mod Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/gta5.png.
        /// </summary>
        public static string Grand_Theft_Auto_V_Dedicated_Server__FiveM_ {
            get {
                return ResourceManager.GetString("Grand Theft Auto V Dedicated Server (FiveM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/hl2dm.png.
        /// </summary>
        public static string Half_Life_2__Deathmatch_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life 2: Deathmatch Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/l4d2.png.
        /// </summary>
        public static string Left_4_Dead_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Left 4 Dead 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mc.png.
        /// </summary>
        public static string Minecraft__Java_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Java Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mcpe.png.
        /// </summary>
        public static string Minecraft__Pocket_Edition_Server__PocketMine_MP_ {
            get {
                return ResourceManager.GetString("Minecraft: Pocket Edition Server (PocketMine-MP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mordhau.png.
        /// </summary>
        public static string Mordhau_Dedicated_Server {
            get {
                return ResourceManager.GetString("Mordhau Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/rust.png.
        /// </summary>
        public static string Rust_Dedicated_Server {
            get {
                return ResourceManager.GetString("Rust Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/se.png.
        /// </summary>
        public static string Space_Engineers_Dedicated_Server {
            get {
                return ResourceManager.GetString("Space Engineers Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/tf2.png.
        /// </summary>
        public static string Team_Fortress_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress 2 Dedicated Server", resourceCulture);
            }
        }
    }
}
