//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsGSM.GameServer.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Icon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsGSM.GameServer.Data.Icon", typeof(Icon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/7dtd.png.
        /// </summary>
        public static string _7_Days_to_Die_Dedicated_Server {
            get {
                return ResourceManager.GetString("7 Days to Die Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/arkse.png.
        /// </summary>
        public static string ARK__Survival_Evolved_Dedicated_Server {
            get {
                return ResourceManager.GetString("ARK: Survival Evolved Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/avorion.png.
        /// </summary>
        public static string Avorion_Dedicated_Server {
            get {
                return ResourceManager.GetString("Avorion Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/bt.png.
        /// </summary>
        public static string Barotrauma_Dedicated_Server {
            get {
                return ResourceManager.GetString("Barotrauma Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/bw.png.
        /// </summary>
        public static string BlackWake_Dedicated_Server {
            get {
                return ResourceManager.GetString("BlackWake Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/ce.png.
        /// </summary>
        public static string Conan_Exiles_Dedicated_Server {
            get {
                return ResourceManager.GetString("Conan Exiles Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/cs.png.
        /// </summary>
        public static string Counter_Strike__1_6_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: 1.6 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/cscz.png.
        /// </summary>
        public static string Counter_Strike__Condition_Zero_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Condition Zero Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/csgo.png.
        /// </summary>
        public static string Counter_Strike__Global_Offensive_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Global Offensive Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/css.png.
        /// </summary>
        public static string Counter_Strike__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Counter-Strike: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/dods.png.
        /// </summary>
        public static string Day_of_Defeat__Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat: Source Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/dod.png.
        /// </summary>
        public static string Day_of_Defeat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Day of Defeat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/dayz.png.
        /// </summary>
        public static string DayZ_Dedicated_Server {
            get {
                return ResourceManager.GetString("DayZ Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/dmc.png.
        /// </summary>
        public static string Deathmatch_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Deathmatch Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/egs.png.
        /// </summary>
        public static string Empyrion___Galactic_Survival_Dedicated_Server {
            get {
                return ResourceManager.GetString("Empyrion - Galactic Survival Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/gmod.png.
        /// </summary>
        public static string Garry_s_Mod_Dedicated_Server {
            get {
                return ResourceManager.GetString("Garry\'s Mod Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/gta5.png.
        /// </summary>
        public static string Grand_Theft_Auto_V_Dedicated_Server__FiveM_ {
            get {
                return ResourceManager.GetString("Grand Theft Auto V Dedicated Server (FiveM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/hlof.png.
        /// </summary>
        public static string Half_Life__Opposing_Force_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life: Opposing Force Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/hl2dm.png.
        /// </summary>
        public static string Half_Life_2__Deathmatch_Dedicated_Server {
            get {
                return ResourceManager.GetString("Half-Life 2: Deathmatch Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/heat.png.
        /// </summary>
        public static string Heat_Dedicated_Server {
            get {
                return ResourceManager.GetString("Heat Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/inss.png.
        /// </summary>
        public static string Insurgency__Sandstorm_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency: Sandstorm Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/ins.png.
        /// </summary>
        public static string Insurgency_Dedicated_Server {
            get {
                return ResourceManager.GetString("Insurgency Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/l4d2.png.
        /// </summary>
        public static string Left_4_Dead_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Left 4 Dead 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mcbe.png.
        /// </summary>
        public static string Minecraft__Bedrock_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Bedrock Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mc.png.
        /// </summary>
        public static string Minecraft__Java_Edition_Server {
            get {
                return ResourceManager.GetString("Minecraft: Java Edition Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mcpe.png.
        /// </summary>
        public static string Minecraft__Pocket_Edition_Server__PocketMine_MP_ {
            get {
                return ResourceManager.GetString("Minecraft: Pocket Edition Server (PocketMine-MP)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/mordhau.png.
        /// </summary>
        public static string Mordhau_Dedicated_Server {
            get {
                return ResourceManager.GetString("Mordhau Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/nmrih.png.
        /// </summary>
        public static string No_More_Room_in_Hell_Dedicated_Server {
            get {
                return ResourceManager.GetString("No More Room in Hell Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/onset.png.
        /// </summary>
        public static string Onset_Dedicated_Server {
            get {
                return ResourceManager.GetString("Onset Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/olow.png.
        /// </summary>
        public static string Outlaws_of_the_Old_West_Dedicated_Server {
            get {
                return ResourceManager.GetString("Outlaws of the Old West Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/rok.png.
        /// </summary>
        public static string Reign_Of_Kings_Dedicated_Server {
            get {
                return ResourceManager.GetString("Reign Of Kings Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/rcc.png.
        /// </summary>
        public static string Ricochet_Dedicated_Server {
            get {
                return ResourceManager.GetString("Ricochet Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/rust.png.
        /// </summary>
        public static string Rust_Dedicated_Server {
            get {
                return ResourceManager.GetString("Rust Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/se.png.
        /// </summary>
        public static string Space_Engineers_Dedicated_Server {
            get {
                return ResourceManager.GetString("Space Engineers Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/sq.png.
        /// </summary>
        public static string Squad_Dedicated_Server {
            get {
                return ResourceManager.GetString("Squad Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/sw.png.
        /// </summary>
        public static string Stormworks_Dedicated_Server {
            get {
                return ResourceManager.GetString("Stormworks Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/tf2.png.
        /// </summary>
        public static string Team_Fortress_2_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress 2 Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/tfc.png.
        /// </summary>
        public static string Team_Fortress_Classic_Dedicated_Server {
            get {
                return ResourceManager.GetString("Team Fortress Classic Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/tf.png.
        /// </summary>
        public static string The_Forest_Dedicated_Server {
            get {
                return ResourceManager.GetString("The Forest Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/unt.png.
        /// </summary>
        public static string Unturned_Dedicated_Server {
            get {
                return ResourceManager.GetString("Unturned Dedicated Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Games/zps.png.
        /// </summary>
        public static string Zombie_Panic_Source_Dedicated_Server {
            get {
                return ResourceManager.GetString("Zombie Panic Source Dedicated Server", resourceCulture);
            }
        }
    }
}
